 spring.datasource.url=jdbc:postgresql://localhost:5433/weekly_planner

spring.datasource.username=postgres
spring.datasource.password=oussama123000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#jwt
security.jwt.secret-key =123456789123456789123456789987654321
security.jwt.expiration-time = 3600000


#mail properties

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=oussama.tagout2015@gmail.com
spring.mail.password="fodhxppbigcjvaof"

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true